name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        name: Build with npm
        run: |
          npm ci
          npm run build
        env:
          CI: true
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
